on:
  push:
    tags: [ v* ]
  workflow_dispatch:

jobs:
  taro_release_job:
    runs-on: ubuntu-latest
    name: Taro Bundle Release
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Cache node_modules Folder
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/app/node_modules
          key: ${{ runner.os }}-node_modules
          restore-keys: ${{ runner.os }}-node_modules
      - name: Get Yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v2
        env:
          cache-name: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        working-directory: ./app
        run: |
          yarn
      - run: |
          cd app
      - name: Release Taro React Native bundle
        uses: zhiqingchen/taro-react-native-release@v1.1
        with:
          workingdirectory: ./app
          token: ${{ secrets.GITHUB_TOKEN }}
          appname: Taro-Mortgage-calculator
          logo: https://pic3.58cdn.com.cn/nowater/fangfe/n_v25b1523466b894881b9bdeda7618a8af2.png
      - name: Upload Qr Image
        uses: actions/upload-artifact@v2
        with:
          name: bundle-qr-code
          path: |
            app/release/qrcode/ios.png
            app/release/qrcode/android.png
