on:
  push:
    tags: [ v* ]
  workflow_dispatch:

jobs:
  taro_release_job:
    runs-on: ubuntu-latest
    name: Taro Bundle Release
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Release Taro React Native bundle
        uses: zhiqingchen/taro-react-native-release@v1.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
